### PR TITLE
breaking: Update AJV to v8

### PR DESCRIPTION
**Pull request by LautaroPetaccio**
This PR updates AJV to its version 8.
There are only a few breaking changes, but as this library exports the validation and the schemas, it will also inherit the breaking change.
[Site with the v8 change logs.](https://github.com/ajv-validator/ajv/releases/tag/v8.0.0)

### CODE REVIEW

**Review by nicosantangelo — APPROVED** [review]

**Comment by menduz** [comment]
Was there any specific reason for this?

**Comment by menduz** [comment]
https://github.com/decentraland/sdk/issues/337

**Comment by menduz** [comment]
Can we have strict versions instead of caret?

**Comment by menduz** [comment]
They may be missing something with semantic releases on their end

**Pull request merged**
